#!/bin/sh
# Simulates reboot by killing entrypoint (PID 1), which restarts the container
echo "Simulating reboot..."
sync
# Kill entrypoint (PID 1) - container will restart due to restart policy
kill 1