#!/bin/sh
# Simulates reboot by killing supervisord (PID 1), which restarts the container
echo "Simulating reboot..."
sync
# Kill supervisord (PID 1) - container will restart due to restart policy
kill 1