#!/bin/sh
PIDFILE=/var/run/dropbear.pid
case "$1" in
  start)
    if [ -f $PIDFILE ]; then
      echo "Dropbear already running"
    else
      dropbear -R -p 2223
      echo "Dropbear started"
    fi
    ;;
  stop)
    if [ -f $PIDFILE ]; then
      kill $(cat $PIDFILE)
      rm -f $PIDFILE
      echo "Dropbear stopped"
    else
      killall dropbear 2>/dev/null
      echo "Dropbear stopped"
    fi
    ;;
  status)
    if pidof dropbear > /dev/null; then
      echo "Dropbear is running"
    else
      echo "Dropbear is not running"
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac