#!/bin/sh
# Dropbear is managed by supervisord, so we use supervisorctl to control it
case "$1" in
  start)
    if pidof dropbear > /dev/null; then
      echo "Dropbear already running"
    else
      supervisorctl start dropbear
      echo "Dropbear started"
    fi
    ;;
  stop)
    if pidof dropbear > /dev/null; then
      supervisorctl stop dropbear
      echo "Dropbear stopped"
    else
      echo "Dropbear already stopped"
    fi
    ;;
  status)
    if pidof dropbear > /dev/null; then
      echo "Dropbear is running"
    else
      echo "Dropbear is not running"
    fi
    ;;
  restart)
    supervisorctl restart dropbear
    echo "Dropbear restarted"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac